'use strict';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const safeStore={get(k){try{return localStorage.getItem(k);}catch{return null;}},set(k,v){try{localStorage.setItem(k,v);}catch{}}};
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let catalog=[],filter='Todos';
function renderCatalog(){const list=catalog.filter(c=>filter==='Todos'||c.category===filter);$('#catalog').innerHTML=list.length?list.map(c=>`<button class="app-card" data-slug="${escapeHTML(c.slug)}" aria-label="Explorar ${escapeHTML(c.title)}"><span class="card-number" aria-hidden="true">${String(c.sort_order).padStart(2,'0')}</span><span class="card-category">${escapeHTML(c.category)} / ${escapeHTML(c.kind)}</span><h3>${escapeHTML(c.title)}</h3><p>${escapeHTML(c.summary)}</p><span class="card-more">Explorar a ideia <span aria-hidden="true">↗</span></span></button>`).join(''):'<p>Nenhuma ideia nesta categoria.</p>';}
function validCatalog(data){return Array.isArray(data)&&data.length>0&&data.every(x=>['slug','category','title','summary','kind','prototype','next_step','review','prompt'].every(k=>typeof x[k]==='string')&&Number.isFinite(x.sort_order));}
async function loadCatalog(){let fallback=false;try{const r=await fetch('catalog.json');const rows=await r.json();if(!validCatalog(rows))throw Error();catalog=rows;renderCatalog();fallback=true;}catch{}const config=window.VIBECODE_CONFIG;try{if(!config?.supabaseUrl||!config?.publishableKey)throw Error('unconfigured');const r=await fetch(config.supabaseUrl+'/rest/v1/vibecode_catalog?select=slug,category,title,summary,kind,prototype,next_step,review,prompt,sort_order&published=eq.true&order=sort_order.asc',{headers:{apikey:config.publishableKey},signal:AbortSignal.timeout(6500)});if(!r.ok)throw Error('fetch');const rows=await r.json();if(!validCatalog(rows))throw Error('empty');catalog=rows;renderCatalog();$('#catalog-status').textContent='Catálogo atualizado a partir do banco de dados.';$('#catalog-status').dataset.source='supabase';}catch{$('#catalog-status').textContent=fallback?'Exibindo o catálogo de apoio. A conexão com o banco está indisponível no momento.':'Não foi possível carregar o catálogo. Atualize a página para tentar novamente.';$('#catalog-status').dataset.source='fallback';}}
$$('.filter').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;$$('.filter').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderCatalog();}));
$('#catalog').addEventListener('click',e=>{const b=e.target.closest('[data-slug]');if(!b)return;const c=catalog.find(x=>x.slug===b.dataset.slug);if(!c)return;$('#detail-content').innerHTML=`<p class="detail-category">${escapeHTML(c.category.toUpperCase())} / ${escapeHTML(c.kind.toUpperCase())}</p><h2>${escapeHTML(c.title)}</h2><p>${escapeHTML(c.summary)}</p><h3>Uma primeira versão</h3><p>${escapeHTML(c.prototype)}</p><h3>Como evoluir</h3><p>${escapeHTML(c.next_step)}</p><h3>O que conferir</h3><p>${escapeHTML(c.review)}</p><h3>Um prompt para começar</h3><p class="detail-prompt">${escapeHTML(c.prompt)}</p><div class="dialog-actions"><button class="btn lime" id="copy-detail">Copiar este prompt</button><p class="small" id="detail-status" role="status"></p></div>`;$('#copy-detail').addEventListener('click',()=>copyText(c.prompt,$('#detail-status')));$('#detail-dialog').showModal();});
$('.close-dialog').addEventListener('click',()=>$('#detail-dialog').close());$('#detail-dialog').addEventListener('click',e=>{if(e.target===$('#detail-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
async function copyText(text,status){try{await navigator.clipboard.writeText(text);status.textContent='Copiado!';}catch{status.textContent='Não foi possível copiar automaticamente. Selecione o texto ou baixe o arquivo.';}}
const templates={game:{name:'um jogo de desviar de obstáculos',flow:'O jogador se move com setas ou A/D. Colidir encerra a partida. Inclua pontuação por tempo e botão de reiniciar.',test:'Verifique movimento, limites da tela, colisão e reinício de duas partidas seguidas.'},quiz:{name:'um quiz interativo',flow:'Mostre uma pergunta por vez, registre as respostas e apresente pontuação e explicações ao final. Use perguntas de exemplo para revisão.',test:'Verifique respostas corretas e incorretas, navegação por teclado e reinício com pontuação zerada.'},event:{name:'um aplicativo de agenda de evento',flow:'Mostre atividades com horário, local e categoria. Inclua filtros. Use programação fictícia identificada como exemplo.',test:'Verifique filtros, horários, estados vazios e legibilidade no celular.'},tool:{name:'um organizador de tarefas',flow:'Permita criar tarefas, definir prazo e marcar como concluídas. Use dados fictícios. Salve a demonstração neste navegador.',test:'Verifique criação, conclusão, filtros e recuperação das tarefas ao recarregar.'}};
function makePrompt(){const t=templates[$('#project-type').value];const audience=$('#audience').value.trim()||'pessoas iniciantes';const extra=$('#extra').value.trim();$('#prompt-output').textContent=`Crie ${t.name} para ${audience}.\n\nFluxo principal: ${t.flow}\n\nDireção visual: ${$('#visual').value}. Priorize bom contraste, controles acessíveis e layout responsivo.${extra?'\n\nCaracterística importante: '+extra+'.':''}\n\nComece com uma versão pequena, sem dependências desnecessárias. Explique como executar.\n\nCritérios de teste: ${t.test} Relate o que verificou e qualquer limitação.\n\nAntes de adicionar serviços externos, explique quais credenciais e custos seriam necessários. Nunca coloque chaves privadas no navegador.`;$('#copy-status').textContent='Prompt atualizado. Pronto para copiar ou baixar.';}
$('#prompt-form').addEventListener('submit',e=>{e.preventDefault();makePrompt();});$('#copy-prompt').addEventListener('click',()=>copyText($('#prompt-output').textContent,$('#copy-status')));$('#download-prompt').addEventListener('click',()=>{const blob=new Blob([$('#prompt-output').textContent],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='meu-prompt-vibecode.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});$('#copy-link').addEventListener('click',()=>copyText(location.href.split('#')[0],$('#link-status')));makePrompt();loadCatalog();
if(window.VIBECODE_CONFIG?.repository){$('#source-link').href=window.VIBECODE_CONFIG.repository;$('#source-link').hidden=false;}
// Presentation mode keeps the actual site interactive, with section navigation.
const sections=$$('.stage-section');let stage=0;function moveStage(n){stage=Math.max(0,Math.min(sections.length-1,n));sections[stage].scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});$('#stage-progress').textContent=`${stage+1} / ${sections.length}`;$('#stage-prev').disabled=stage===0;$('#stage-next').disabled=stage===sections.length-1;}
function toggleStage(on){document.body.classList.toggle('stage-mode',on);$('#stage-toolbar').hidden=!on;$('#present').setAttribute('aria-pressed',String(on));if(on)moveStage(0);}
$('#present').addEventListener('click',()=>toggleStage(!document.body.classList.contains('stage-mode')));$('#stage-prev').addEventListener('click',()=>moveStage(stage-1));$('#stage-next').addEventListener('click',()=>moveStage(stage+1));$('#stage-exit').addEventListener('click',()=>toggleStage(false));
document.addEventListener('keydown',e=>{if(!document.body.classList.contains('stage-mode')||/INPUT|SELECT|TEXTAREA|CANVAS/.test(e.target.tagName)||$('#detail-dialog').open)return;if(e.key==='Escape')toggleStage(false);if(e.key==='PageDown'){e.preventDefault();moveStage(stage+1);}if(e.key==='PageUp'){e.preventDefault();moveStage(stage-1);}});
